config/routes.rb
Rails.application.routes.draw do
  resources :genres, param: :slug

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do 
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end
  root "movies#index"

  resource  :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
  
  resources :users, param: :username
  get "signup" => "users#new"
end

app/models/genre.rb
class Genre < ApplicationRecord
  before_save :set_slug

  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations
  
  validates :name, presence: true, uniqueness: true 
  validates :slug, presence: true, uniqueness: true

  def to_param
    slug
  end

private 
  def set_slug
    self.slug = name.parameterize if name.present?
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  before_action :set_genre, except: [:index, :new, :create]

  def index
    @genres = Genre.all      
  end

  def show
    @movies = @genre.movies
  end
  

  def new
    @genre = Genre.new     
  end

  def create
    @genre = Genre.new(genre_params)      
    if @genre.save
      redirect_to @genre, notice: "Genre created successfully."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      redirect_to @genre, notice: "Genre updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    @genre.destroy
    redirect_to genres_path, notice: "Genre deleted successfully!"
  end

  private

  def set_genre
    @genre = Genre.find_by!(slug: params[:slug])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: @genre, local: true, class: "genre-form") do |form| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation" class="error-messages">
      <h2><%= pluralize(@genre.errors.count, "error") %> this genre could not be saved!</h2>
      <ul>
        <% @genre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Name of Genre" %>
    <%= form.text_field :name, class: "form-input" %>
  </div>

  <div class="actions">
    <%= form.submit class: "submit-button" %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Go back to list', genres_path %>

app/views/genres/index.html.erb
<h1>Genres</h1>

<%= link_to 'New Genre', new_genre_path, class: "button" %>

<ul class="genres-list">
  <% @genres.each do |genre| %>
    <li class="genre-item">
      <%= link_to genre.name, genre_path(genre.slug), class: "genre-name" %>
    </li>
  <% end %>
</ul>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render "form", genre: @genre %>

<%= link_to 'Go back to list', genres_path, class: "button" %>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<h2>Movies in this Genre:</h2>

<ul>
  <% @movies.each do |movie| %>
    <li><%= link_to movie.title, movie_path(movie) %></li>
  <% end %>
</ul>

<% if current_user.admin? %>
  <%= link_to 'Edit Genre', edit_genre_path(@genre), class: "btn btn-warning" %>
  <%= link_to 'Delete Genre', genre_path(@genre), class: "btn btn-danger", 
        data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        <%= link_to 'Go back to list', genres_path %>
<% end %>