config/routes.rb
Rails.application.routes.draw do
  resources :genres, param: :slug

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do 
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end
  root "movies#index"

  resource  :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
  
  resources :users, param: :username
  get "signup" => "users#new"
end

app/models/movie.rb
class Movie < ApplicationRecord
  before_save :set_slug

  has_many :reviews, dependent: :destroy
  has_many :critics, through: :reviews, source: :user
  
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user

  has_many :characterizations, dependent: :destroy
  has_many :genres, through: :characterizations

  validates :title, presence: true, uniqueness: true

  validates :released_on, :duration, presence: true

  validates :description, length: { minimum:25 }

  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }

  validates :image_file_name, format: {
  with: /\w+\.(jpg|png)\z/i,
  message: "must be a JPG or PNG image"
  }

  RATINGS = %w(G PG PG-13 R NC-17)
    validates :rating, inclusion: { in: RATINGS }

  scope :released, -> { where("released_on < ?", Time.now).order("released_on desc")}
  scope :upcoming, -> { where("released_on < ?", Time.now).order("released_on asc")}
  scope :recent, ->(max=5) { released.limit(max)}
  
  scope :hits, -> { released.where("total_gross >= 300000000").order(total_gross: :desc) }
  scope :flops, -> { released.where("total_gross < 225000000").order(total_gross: :asc) }

  scope :grossed_less_than, ->(amount) { where("total_gross < ?", amount) }
  scope :grossed_greater_than, ->(amount) { where("total_gross > ?", amount) }

  

  def flop?
    unless (reviews.count > 50 && average_stars >= 4)
      (total_gross.blank? || total_gross < 225_000_000)
    end
  end

  def average_stars
    reviews.average(:stars) || 0.0
  end

  def average_stars_as_percent
    (self.average_stars / 5.0) * 100
  end

  def to_param
    slug
  end
private 
  
  def set_slug
    self.slug = title.parameterize
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  
  def index
    @movies = Movie.send(movies_filter)
  end
  
  def show
    @fans = @movie.fans
    @genres = @movie.genres.order(:name)
    if current_user
      @favorite = current_user.favorites.find_by(movie_id: @movie.id)
    end
  end

  def edit

  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: "Movie successfully updated!"
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  def new 
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Movie successfully updated!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_url, status: :see_other, 
    alert: "Movie succesfully deleted" 
  end


private 
  def movie_params
    params.require(:movie).
    permit(:title, :description, :rating, :released_on, :total_gross, :director,
      :duration, :image_file_name, genre_ids: [])
  end

  def movies_filter
    if params[:filter].in? %w(upcoming recent hits flops)
      params[:filter]
    else
      :released
    end
  end

  def set_movie
    @movie = Movie.find_by!(slug: params[:id])
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def total_gross(movie)
    movie.flop? ? "Flop!" : number_to_currency(movie.total_gross, precision: 0)
  end

  def year_of(movie)
    movie.released_on&.year
  end

  def nav_link_to(text, url)
    link_to(text, url, class: current_page?(url) ? "active" : nil)
  end
end

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |f|%>

    <%= render "shared/errors", object: movie %>

    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true  %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 10 %>

    <%= f.label :rating%>
    <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>

    <%= f.label :released_on%>
    <%= f.date_field :released_on %>

    <%= f.label :total_gross %>
    <%= f.number_field :total_gross %>

    <%= f.label :director %>
    <%= f.text_field :director %>

    <%= f.label :duration %>
    <%= f.text_field :duration %>

    <%= f.label :image_file_name %>
    <%= f.text_field :image_file_name %>

    <div class="checkboxes">
        <%= f.collection_check_boxes(:genre_ids, Genre.order(:name), :id, :name) %>
    </div>
    
    <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing <%= @movie.title%></h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <section class="movie">
    <div class="image">
      <%= image_tag movie.image_file_name %>
    </div>
    <div class="summary">
      <h2>
        <%= link_to movie.title, movie_path(movie) %>
      </h2>
      <h3>
        <%= total_gross(movie) %>
      </h3>
       <span class="stars">
         <%= render "shared/stars", percent: movie.average_stars_as_percent %>
       </span>
      <p>
        <%= truncate(movie.description, length: 150, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>

<% if current_user_admin? %>
<section class="admin">
  <%= link_to "Add a new movie", new_movie_path, class: "button" %>
</section>
<% end %>

app/views/movies/new.html.erb
<h1>Create a new Movie</h1>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<section class="movie-details">
  <div class="image">
    <%= image_tag @movie.image_file_name %>
    <% if current_user %>
      <div class="faves">
        <%= fave_or_unfave_button(@movie, @favorite) %>
        <div class="count">
          <%= @fans.size %>
        </div>
      </div>
    <% end %>
  </div>
  
  <div class="details">
    <h1><%= @movie.title %></h1>
    <h2>
      <%= year_of(@movie) %> &bull; <%= @movie.rating %>
    </h2>
    <div class="reviews">
      <%= render "shared/stars", percent: @movie.average_stars_as_percent %>
      <%= link_to pluralize(@movie.reviews.size, "review"), movie_reviews_path(@movie) %>
    </div>
    <p>
      <%= @movie.description %>
    </p>
    <table>
      <tr>
        <th>Director:</th>
        <td><%= @movie.director %></td>
      </tr>
      <tr>
        <th>Duration:</th>
        <td><%= @movie.duration %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
        <td><%= total_gross(@movie) %></td>
      </tr>
    </table>
    <%= link_to "Write Review", new_movie_review_path(@movie), class: "review" %>
  </div>

  <aside>
    <% if @fans.present? %>
      <h4>Fans</h4>
      <ul>
        <% @fans.each do |user| %>
          <li>
            <%= link_to user.name, user %>
            <%= profile_image(user, 20) %>
          </li>
        <% end %>
      </ul>
    <% end %>

    <% if @genres.present? %>
      <h4>
        <%= link_to 'Genres', genres_path, class: 'genre-title' %>
      </h4>
      <ul>
        <% @genres.each do |g| %>
          <li><%= link_to g.name, genres_path %></li>
        <% end %>
      </ul>
    <% end %>
  </aside>
</section>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
    <%= link_to "Delete", movie_path(@movie), class: "button", 
        data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </section>
<% end %>