config/routes.rb
Rails.application.routes.draw do
  resources :genres, param: :slug

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do 
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end
  root "movies#index"

  resource  :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
  
  resources :users, param: :username
  get "signup" => "users#new"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_movies, through: :favorites, source: :movie

  before_save :format_username
  before_save :format_email

  validates :name, presence: true

  validates :password, length: { minimum: 10, allow_blank: true }

  validates :username, presence: true, 
                       uniqueness: { case_sensitive: false }, 
                       format: { with: /\A[A-Z0-9]+\z/i }
  
  

  validates :email, presence: true,
                  format: { with: /\S+@\S+/ },
                  uniqueness: { case_sensitive: false }

  scope :by_name, -> { order(:name) }
  scope :not_admins, -> { by_name.where(admin: false) }

  def gravatar_id
   Digest::MD5::hexdigest(email.downcase)
  end

  def format_username
    self.username = username.downcase
  end

  def format_email
    self.email = email.downcase
  end

  def to_param
    username
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.not_admins
  end

  def show
    @user = User.find_by!(username: params[:username])
    @reviews = @user.reviews
  end

  def edit
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Account was successfully updated!"
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil 
    redirect_to movies_url, status: :see_other,
     alert: "Account successfully deleted!"
  end
  

private 

  def user_params
    params.require(:user).
    permit(:name,:email, :password, :password_confirmation, :username)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_url, status: :see_other unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_image(user, size = 80)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(url, alt: user.name)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |f| %>
    <%= render 'shared/errors', object: user %>

    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>

    <%= f.label :username %>
    <%= f.text_field :username, placeholder: "Alphanumeric characters only!" %>

    <%= f.label :email %>
    <%= f.email_field :email%>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation%>

    <% if user.new_record? %>
        <%= f.submit "Create Account"%>
    <% else %>
        <%= f.submit "Update Account"%>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>
<ul class="users">
    <% @users.each do |user| %>
    <li>
        <%= link_to user.name, user_path(user.username) %>
        created
        <%= time_ago_in_words(user.created_at) %> ago
    </li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
  <%= profile_image(@user) %>
  <h1><%= @user.name %></h1>
  <h2><%= @user.username %></h2>
  <h3><%= mail_to(@user.email) %></h3>
  <div class="actions">
    <% if current_user?(@user) %>
      <%= link_to "Edit Account", edit_user_path(@user),
                  class: "button edit" %>
      <%= link_to "Delete Account", @user, 
                  data: { 
                    turbo_method: :delete, 
                    turbo_confirm: "Permanently delete your account!?"
                  },
                  class: "button delete" %>
    <% end %>
  </div>
  <% if @reviews.present? %>
    <h3>Reviews</h3>
    <% @reviews.each do |review| %>
      <div class="review">
        <div class="details">
          <%= profile_image(review.user, 35) %>
          <span class="title">
            <%= link_to review.movie.title, review.movie %>
          </span>
          <%= pluralize(review.stars, 'star') %>
          <span class="date">
            <%= time_ago_in_words(review.created_at) %> ago
          </span>
          <p>
            <%= review.comment %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>
  <h3>Member Since</h3>
  <p>
    <%= @user.created_at.strftime("%B %Y") %>
  </p>
</section>